version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .docker/default.conf:/etc/nginx/conf.d/default.conf
    expose: 
      - "8000"
    depends_on: 
      - nodejs
    networks:                
      - internal-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s .docker/entrypoint.sh
    container_name: nodejs
    tty: true
    restart: always
    volumes:
      - .:/home/node/app
    expose: 
      - "8001"
    depends_on: 
      - mysql
    networks:                
      - internal-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    expose: 
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    networks:                
      - internal-network
    
networks: 
  internal-network:
    driver: bridge
